### ISSUE TITLE
I run the code with tensorflow 2.1.0

### ISSUE THREAD

**Issue by m1nt07** [xuannianz/keras-CenterNet#27]
Thank you for your amazing work!
I run the code on my PC with tensorflow 2.1.0, and replace the keras package with tensorflow.compat.v1.keras, considering the different version of tensorflow. For example,
```
import tensorflow.compat.v1 as tf
import tensorflow.compat.v1.keras
import tensorflow.compat.v1.keras.backend as K
from tensorflow.compat.v1.keras.optimizers import Adam, SGD
import tensorflow.compat.v1.keras.preprocessing.image
# import tensorflow as tf
# import keras
# import keras.backend as K
# from keras.optimizers import Adam, SGD
# import keras.preprocessing.image
```
But I run into the problem at 331 line in train.py,
`model.compile(optimizer=Adam(lr=1e-3), loss={'centernet_loss': lambda y_true, y_pred: y_pred})`

The error is as follows:
```
Traceback (most recent call last):
  File "/home/m1nt/Programmer/Anaconda/envs/py37_keras/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1619, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index -1 of dimension 0 out of bounds. for 'loss/centernet_loss_loss/strided_slice' (op: 'StridedSlice') with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <-1>, input[2] = <0>, input[3] = <1>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m1nt/Programmer/Projects/Pycharm/sec_thesis/keras-CenterNet-master/train.py", line 366, in <module>
    main()
  File "/home/m1nt/Programmer/Projects/Pycharm/sec_thesis/keras-CenterNet-master/train.py", line 331, in main
    model.compile(optimizer=Adam(lr=1e-3), loss={'centernet_loss': lambda y_true, y_pred: y_pred})
  File "/home/m1nt/Programmer/Anaconda/envs/py37_keras/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/m1nt/Programmer/Anaconda/envs/py37_keras/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 446, in compile
    self._compile_weights_loss_and_weighted_metrics()
  File "/home/m1nt/Programmer/Anaconda/envs/py37_keras/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/m1nt/Programmer/Anaconda/envs/py37_keras/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1592, in _compile_weights_loss_and_weighted_metrics
    self.total_loss = self._prepare_total_loss(masks)
  File "/home/m1nt/Programmer/Anaconda/envs/py37_keras/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1652, in _prepare_total_loss
    per_sample_losses = loss_fn.call(y_true, y_pred)
  File "/home/m1nt/Programmer/Anaconda/envs/py37_keras/lib/python3.7/site-packages/tensorflow_core/python/keras/losses.py", line 220, in call
    y_pred, y_true)
  File "/home/m1nt/Programmer/Anaconda/envs/py37_keras/lib/python3.7/site-packages/tensorflow_core/python/ops/losses/util.py", line 79, in squeeze_or_expand_dimensions
    is_last_dim_1 = math_ops.equal(1, array_ops.shape(y_pred)[-1])
  File "/home/m1nt/Programmer/Anaconda/envs/py37_keras/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 898, in _slice_helper
    name=name)
  File "/home/m1nt/Programmer/Anaconda/envs/py37_keras/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 1064, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/home/m1nt/Programmer/Anaconda/envs/py37_keras/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 9535, in strided_slice
    shrink_axis_mask=shrink_axis_mask, name=name)
  File "/home/m1nt/Programmer/Anaconda/envs/py37_keras/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 742, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/home/m1nt/Programmer/Anaconda/envs/py37_keras/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 595, in _create_op_internal
    compute_device)
  File "/home/m1nt/Programmer/Anaconda/envs/py37_keras/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3322, in _create_op_internal
    op_def=op_def)
  File "/home/m1nt/Programmer/Anaconda/envs/py37_keras/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1786, in __init__
    control_input_ops)
  File "/home/m1nt/Programmer/Anaconda/envs/py37_keras/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1622, in _create_c_op
    raise ValueError(str(e))
ValueError: slice index -1 of dimension 0 out of bounds. for 'loss/centernet_loss_loss/strided_slice' (op: 'StridedSlice') with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <-1>, input[2] = <0>, input[3] = <1>.
```
I don't know how to solve it, so I want to ask for your help.
Thank you! Have a nice day!

**Comment by castrorpc** [comment]
Também estou com erro parecido:
 File "C:\Users\User\anaconda3\envs\ENV_RPC_37v2\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1619, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)

InvalidArgumentError: slice index -1 of dimension 0 out of bounds. for 'metrics/mean_absolute_error/strided_slice' (op: 'StridedSlice') with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <-1>, input[2] = <0>, input[3] = <1>.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\User\Google Drive\Dissertação do Mestrado\Modelo\Tito\V2\__init__.py", line 5, in <module>
    model = build_model(2, 2) # Instance of the model

  File "C:\Users\User\Google Drive\Dissertação do Mestrado\Modelo\Tito\V2\ANFIS_Model.py", line 34, in build_model
    ANFIS_Model.compile(optimizer='adam', loss='mean_squared_error', metrics=metrics)

  File "C:\Users\User\anaconda3\envs\ENV_RPC_37v2\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)

  File "C:\Users\User\anaconda3\envs\ENV_RPC_37v2\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 439, in compile
    masks=self._prepare_output_masks())

  File "C:\Users\User\anaconda3\envs\ENV_RPC_37v2\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 2004, in _handle_metrics
    target, output, output_mask))

  File "C:\Users\User\anaconda3\envs\ENV_RPC_37v2\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1955, in _handle_per_output_metrics
    metric_fn, y_true, y_pred, weights=weights, mask=mask)

  File "C:\Users\User\anaconda3\envs\ENV_RPC_37v2\lib\site-packages\tensorflow_core\python\keras\engine\training_utils.py", line 1155, in call_metric_function
    return metric_fn(y_true, y_pred, sample_weight=weights)

  File "C:\Users\User\anaconda3\envs\ENV_RPC_37v2\lib\site-packages\tensorflow_core\python\keras\metrics.py", line 196, in __call__
    replica_local_fn, *args, **kwargs)

  File "C:\Users\User\anaconda3\envs\ENV_RPC_37v2\lib\site-packages\tensorflow_core\python\keras\distribute\distributed_training_utils.py", line 1135, in call_replica_local_fn
    return fn(*args, **kwargs)

  File "C:\Users\User\anaconda3\envs\ENV_RPC_37v2\lib\site-packages\tensorflow_core\python\keras\metrics.py", line 179, in replica_local_fn
    update_op = self.update_state(*args, **kwargs)  # pylint: disable=not-callable

  File "C:\Users\User\anaconda3\envs\ENV_RPC_37v2\lib\site-packages\tensorflow_core\python\keras\utils\metrics_utils.py", line 76, in decorated
    update_op = update_state_fn(*args, **kwargs)

  File "C:\Users\User\anaconda3\envs\ENV_RPC_37v2\lib\site-packages\tensorflow_core\python\keras\metrics.py", line 585, in update_state
    y_pred, y_true)

  File "C:\Users\User\anaconda3\envs\ENV_RPC_37v2\lib\site-packages\tensorflow_core\python\ops\losses\util.py", line 79, in squeeze_or_expand_dimensions
    is_last_dim_1 = math_ops.equal(1, array_ops.shape(y_pred)[-1])

  File "C:\Users\User\anaconda3\envs\ENV_RPC_37v2\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 898, in _slice_helper
    name=name)

  File "C:\Users\User\anaconda3\envs\ENV_RPC_37v2\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 1064, in strided_slice
    shrink_axis_mask=shrink_axis_mask)

  File "C:\Users\User\anaconda3\envs\ENV_RPC_37v2\lib\site-packages\tensorflow_core\python\ops\gen_array_ops.py", line 9534, in strided_slice
    shrink_axis_mask=shrink_axis_mask, name=name)

  File "C:\Users\User\anaconda3\envs\ENV_RPC_37v2\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 742, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)

  File "C:\Users\User\anaconda3\envs\ENV_RPC_37v2\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 595, in _create_op_internal
    compute_device)

  File "C:\Users\User\anaconda3\envs\ENV_RPC_37v2\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3322, in _create_op_internal
    op_def=op_def)

  File "C:\Users\User\anaconda3\envs\ENV_RPC_37v2\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1786, in __init__
    control_input_ops)

  File "C:\Users\User\anaconda3\envs\ENV_RPC_37v2\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1622, in _create_c_op
    raise ValueError(str(e))

ValueError: slice index -1 of dimension 0 out of bounds. for 'metrics/mean_absolute_error/strided_slice' (op: 'StridedSlice') with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <-1>, input[2] = <0>, input[3] = <1>.

**Comment by luoqishuai** [comment]
@m1nt07 @castrorpc 
How did you solve the problem?
