### ISSUE TITLE
Max_Objects > 100 will raise error

### ISSUE THREAD

**Issue by chuong-phung** [xuannianz/keras-CenterNet#30]
I have train on own dataset.
In an image, I have more than 100 objects. The code will raise an error :
`/keras-CenterNet/generators/common.py", line 419, in compute_inputs
    batch_indices[b, i] = ct_int[1] * self.output_size + ct_int[0]
IndexError: index 100 is out of bounds for axis 1 with size 100
`
If I change "max_object=1000" at line 28 in common.py, will get an error:
`Traceback (most recent call last):
  File "train.py", line 356, in <module>
    main()
  File "train.py", line 351, in main
    validation_data=validation_generator
  File "/home/po/anaconda3/envs/keras_centernet/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/po/anaconda3/envs/keras_centernet/lib/python3.6/site-packages/keras/engine/training.py", line 1658, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/po/anaconda3/envs/keras_centernet/lib/python3.6/site-packages/keras/engine/training_generator.py", line 215, in fit_generator
    class_weight=class_weight)
  File "/home/po/anaconda3/envs/keras_centernet/lib/python3.6/site-packages/keras/engine/training.py", line 1443, in train_on_batch
    class_weight=class_weight)
  File "/home/po/anaconda3/envs/keras_centernet/lib/python3.6/site-packages/keras/engine/training.py", line 757, in _standardize_user_data
    exception_prefix='input')
  File "/home/po/anaconda3/envs/keras_centernet/lib/python3.6/site-packages/keras/engine/training_utils.py", line 141, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected input_3 to have shape (100, 2) but got array with shape (1000, 2)
`

**Comment by huynhtnhut97** [comment]
i have the same issues

**Comment by huynhtnhut97** [comment]
a temporary measure is that insert `if i >= 100:
                     break` in common.py line 394

**Comment by chuong-phung** [comment]
@huynhtnhut97 ,
You can change the 

- > max_objects at line 113, model/resnet.py file to fix that problem

from:
def centernet(num_classes, backbone='resnet50', input_size=512, max_objects=100, score_threshold=0.1,
              nms=True,
              flip_test=False,
              freeze_bn=True):
to:
def centernet(num_classes, backbone='resnet50', input_size=512, max_objects=1000, score_threshold=0.1,
              nms=True,
              flip_test=False,
              freeze_bn=True):

**Comment by WuChannn** [comment]
thank you both of you, there is solution for others:
1. change "max_object=1000" at line 28 in generators/common.py
2. change the max_objects=1000 at line 113, model/resnet.py file

the reason why this problem occurs is that the output of our model is more than 100
