### ISSUE TITLE
Face some problem when train on my own dataset in csv format...

### ISSUE THREAD

**Issue by cuiziteng** [xuannianz/keras-CenterNet#33]

**Comment by keersujiade** [comment]
> Hi, I wanna train this model on my own dataset, which only has one object category, and write in csv file , but when I trian this network, I found an error that in \keras-CenterNet-master\generators\csv_.py in line 57-58:
> if class_name in result:
> raise ValueError('line {}: duplicate class name: '{}''.format(line, class_name))
> result[class_name] = class_id
> you know I only have one object category, so how should I change my code or how should I change my class.csv file, thx~

**Comment by WuChannn** [comment]
@keersujiade 您好，我在使用自己的CSV文件训练时遇到了以下问题

Traceback (most recent call last):
  File "train.py", line 356, in <module>
    main()
  File "train.py", line 351, in main
    validation_data=validation_generator
  File "/root/data/anaconda3/envs/CenterNet-Keras/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/root/data/anaconda3/envs/CenterNet-Keras/lib/python3.6/site-packages/keras/engine/training.py", line 1658, in fit_generator
    initial_epoch=initial_epoch)
  File "/root/data/anaconda3/envs/CenterNet-Keras/lib/python3.6/site-packages/keras/engine/training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "/root/data/anaconda3/envs/CenterNet-Keras/lib/python3.6/site-packages/keras/utils/data_utils.py", line 616, in get
    six.reraise(*sys.exc_info())
  File "/root/data/anaconda3/envs/CenterNet/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/root/data/anaconda3/envs/CenterNet-Keras/lib/python3.6/site-packages/keras/utils/data_utils.py", line 603, in get
    inputs = future.get(timeout=30)
  File "/root/data/anaconda3/envs/CenterNet-Keras/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/root/data/anaconda3/envs/CenterNet-Keras/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/root/data/anaconda3/envs/CenterNet-Keras/lib/python3.6/site-packages/keras/utils/data_utils.py", line 406, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/root/data/ks/code/keras-CenterNet/generators/common.py", line 521, in __getitem__
    inputs, targets = self.compute_inputs_targets(group)
  File "/root/data/ks/code/keras-CenterNet/generators/common.py", line 498, in compute_inputs_targets
    inputs = self.compute_inputs(image_group, annotations_group)
  File "/root/data/ks/code/keras-CenterNet/generators/common.py", line 414, in compute_inputs
    batch_whs[b, i] = 1. * w, 1. * h
IndexError: index 100 is out of bounds for axis 1 with size 100

请问您这边知道如何解决吗？谢谢
