### ISSUE TITLE
Can't sve my model?why

### ISSUE THREAD

**Issue by cuiziteng** [xuannianz/keras-CenterNet#34]
like this,why it has val_loss?
Traceback (most recent call last):
  File "train.py", line 356, in <module>
    main()
  File "train.py", line 351, in main
    validation_data=validation_generator
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py", line 260, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.6/dist-packages/keras/callbacks/callbacks.py", line 152, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python3.6/dist-packages/keras/callbacks/callbacks.py", line 702, in on_epoch_end
    filepath = self.filepath.format(epoch=epoch + 1, **logs)
KeyError: 'val_loss'

**Comment by cuiziteng** [comment]
Ok,I've found where to change, just remove something in the checkpoint name...
