### ISSUE TITLE
Got an error when train model with coco data

### ISSUE THREAD

**Issue by zhaozilongwhu** [xuannianz/keras-CenterNet#42]
I got an error when i train model with coco data.

The command is:
python3 train.py --snapshot ~/data/deepfashiondata/model/ResNet-50-model.keras.h5 --freeze-backbone --gpu 0 --random-transform --compute-val-loss --batch-size 1 --steps 1000  coco  ~/data/deepfashiondata/smalldata

The error message is:
_____________________________________________________________________________
Epoch 1/200
Traceback (most recent call last):
  File "train.py", line 357, in <module>
    main()
  File "train.py", line 352, in main
    validation_data=validation_generator
  File "/home/zhaozilong/.local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/zhaozilong/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1658, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/zhaozilong/.local/lib/python3.6/site-packages/keras/engine/training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "/home/zhaozilong/.local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 616, in get
    six.reraise(*sys.exc_info())
  File "/home/zhaozilong/.local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/zhaozilong/.local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 603, in get
    inputs = future.get(timeout=30)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/zhaozilong/.local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 406, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/home/zhaozilong/thirdparty/keras-CenterNet/generators/common.py", line 526, in __getitem__
    inputs, targets = self.compute_inputs_targets(group)
  File "/home/zhaozilong/thirdparty/keras-CenterNet/generators/common.py", line 503, in compute_inputs_targets
    inputs = self.compute_inputs(image_group, annotations_group)
  File "/home/zhaozilong/thirdparty/keras-CenterNet/generators/common.py", line 413, in compute_inputs
    heatmap_temp = batch_hms[b, :, :, cls_id]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
-----------------------------------------------------------------------------------------------------------------------------------

**Comment by xo28** [comment]
Hi Zilong, I'm working on a coco format dataset now. Do you successfully train on a coco dataset?  How do you deal with the input data? Like, do you change some code to let the model read json file?  Because this repo only have example of pascal dataset.
Thanks.

**Comment by WuChannn** [comment]
@zhaozilongwhu have you solve this problem? thanks
